// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqO1dmdTjgz5tCcTNFxBnqun1PfEQB_s',
    appId: '1:167279676919:web:ee36a148470e917732b2f2',
    messagingSenderId: '167279676919',
    projectId: 'study-app-60be4',
    authDomain: 'study-app-60be4.firebaseapp.com',
    storageBucket: 'study-app-60be4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0FmhcJbSptmttlVLNW304qiu5oUqzpSc',
    appId: '1:167279676919:android:6933e296533566f632b2f2',
    messagingSenderId: '167279676919',
    projectId: 'study-app-60be4',
    storageBucket: 'study-app-60be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9A2SomqsuWAA6Z1uQ9WCBMicpvnRy0Sc',
    appId: '1:167279676919:ios:48b5fd81edfa313032b2f2',
    messagingSenderId: '167279676919',
    projectId: 'study-app-60be4',
    storageBucket: 'study-app-60be4.appspot.com',
    iosClientId: '167279676919-fe8tjtntqr20h1v25mlprspk6rlsj33g.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9A2SomqsuWAA6Z1uQ9WCBMicpvnRy0Sc',
    appId: '1:167279676919:ios:48b5fd81edfa313032b2f2',
    messagingSenderId: '167279676919',
    projectId: 'study-app-60be4',
    storageBucket: 'study-app-60be4.appspot.com',
    iosClientId: '167279676919-fe8tjtntqr20h1v25mlprspk6rlsj33g.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzApp',
  );
}
